-- V1__init_schema.sql  (PostgreSQL)

-- 0) Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Core: users
CREATE TABLE IF NOT EXISTS users (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email              citext NOT NULL UNIQUE,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  subscription_tier VARCHAR(20) DEFAULT 'FREE',
  stripe_customer_id text,
  dashboard_preset VARCHAR(50),
  training_style VARCHAR(50),
  training_focus VARCHAR(50)
);

-- add enum constraint on users for dashboard preset
ALTER TABLE users
ADD CONSTRAINT chk_users_dashboard_preset
    CHECK (dashboard_preset IN ('wellness','performance','body') OR dashboard_preset IS NULL);

-- 2) Leads
CREATE TABLE IF NOT EXISTS leads (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL,
  name          text,
  source        text,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);

-- 3) Email verifications
CREATE TABLE IF NOT EXISTS email_verifications (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL,
  access_token  text NOT NULL UNIQUE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz
);
CREATE INDEX IF NOT EXISTS idx_email_verifications_email ON email_verifications(email);
CREATE INDEX IF NOT EXISTS idx_email_verifications_access_token ON email_verifications(access_token);

-- Providers lookup (smallint PK as you moved to)
CREATE TABLE IF NOT EXISTS providers (
  id         smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  auth_type  varchar(20),
  authorize_url     varchar(50),
  name       varchar(20) NOT NULL,
  active     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Seed common providers (idempotent)
INSERT INTO providers (auth_type, name, active) VALUES
  ('oauth1', 'garmin', true),
  ('oauth2', 'fitbit', true),
  ('oauth2', 'oura', true);

-- 4) Provider accounts (Garmin/Fitbit/Strava, etc.)
CREATE TABLE IF NOT EXISTS provider_accounts (
  id               uuid PRIMARY KEY,
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider_id      integer NOT NULL REFERENCES providers(id),                             -- 'garmin' | 'fitbit' | 'strava' ...
  provider_user_id text,                                      -- external user id
  access_token     text,                                      -- V5: tokens -> text
  refresh_token    text,
  expires_at       timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, provider_id)
);
CREATE INDEX IF NOT EXISTS idx_provider_accounts_user ON provider_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_provider_accounts_provider ON provider_accounts(provider_id);

-- 5) User sessions (V9)
CREATE TABLE IF NOT EXISTS user_sessions (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id                     uuid        NOT NULL,         -- FK -> users(id)

  refresh_token               text        NOT NULL UNIQUE,
  refresh_token_expires_at    timestamptz NOT NULL,
  revoked_at                  timestamptz,

  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id  ON user_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expiry   ON user_sessions (refresh_token_expires_at);
CREATE INDEX IF NOT EXISTS idx_user_sessions_revoked  ON user_sessions (revoked_at);





-- !! VERIFY FROM HERE BELOW FOR LOCAL TESTING !!



-- 6) Fitbit users (minimal; tie back to users/provider_accounts as you prefer)
CREATE TABLE IF NOT EXISTS fitbit_users (
  id                bigserial PRIMARY KEY,
  user_id           uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fitbit_user_id    text NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  access_token      text,
  refresh_token     text,
  expires_at        timestamptz,
  UNIQUE (user_id),
  UNIQUE (fitbit_user_id)
);

-- 7) Garmin data tables (based on your screenshot list)
-- You may choose user_id or provider_account_id as FK; using user_id for simplicity.
-- Store rich payloads in raw jsonb so you can evolve columns later.


CREATE TABLE IF NOT EXISTS garmin_activities (
  id                                              uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- JPA: provider_user_id (String, not null)
  provider_user_id                                text        NOT NULL,

  -- JPA: actualizeUserId -> column "user_id" (UUID, not null)
  user_id                                         uuid        NOT NULL,

  summary_id                                      text,
  calendar_date                                   date,

  -- JPA: activityId (Long) with @Column(unique = true)
  activity_id                                     bigint      UNIQUE,

  activity_name                                   text,
  activity_description                            text,

  is_parent                                       boolean,
  parent_summary_id                               text,

  duration_in_seconds                              integer,
  start_time_in_seconds                            bigint,
  start_time_offset_in_seconds                     integer,

  activity_type                                   text,

  average_bike_cadence_in_rounds_per_minute       double precision,
  average_heart_rate_in_beats_per_minute          integer,
  average_run_cadence_in_steps_per_minute         integer,
  average_push_cadence_in_pushes_per_minute       integer,
  average_speed_in_meters_per_second              double precision,
  average_swim_cadence_in_strokes_per_minute      integer,
  average_pace_in_minutes_per_kilometer           double precision,

  active_kilocalories                             integer,
  device_name                                     text,
  distance_in_meters                              double precision,

  max_bike_cadence_in_rounds_per_minute           integer,
  max_heart_rate_in_beats_per_minute              integer,
  max_pace_in_minutes_per_kilometer               double precision,
  max_run_cadence_in_steps_per_minute             integer,
  max_push_cadence_in_pushes_per_minute           integer,
  max_speed_in_meters_per_second                  double precision,

  number_of_active_lengths                        integer,
  starting_latitude_in_degree                     double precision,
  starting_longitude_in_degree                    double precision,

  steps                                           integer,
  pushes                                          integer,
  total_elevation_gain_in_meters                  double precision,
  total_elevation_loss_in_meters                  double precision,

  manual                                          boolean,
  is_web_upload                                   boolean
);
CREATE INDEX IF NOT EXISTS idx_garmin_activities_user        ON garmin_activities (user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_activities_providerusr ON garmin_activities (provider_user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_activities_cal_date    ON garmin_activities (calendar_date);

CREATE TABLE IF NOT EXISTS garmin_daily_summaries (
  id                                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  summary_id                              text,

  provider_user_id                        text        NOT NULL,
  user_id                                 uuid        NOT NULL,   -- FK -> users.id

  calendar_date                           date,

  steps                                   integer,
  steps_goal                              integer,
  distance_in_meters                      double precision,

  active_kilocalories                     integer,
  bmr_kilocalories                        integer,

  duration_in_seconds                     integer,
  active_time_in_seconds                  integer,

  average_stress_level                    integer,
  max_stress_level                        integer,

  low_stress_duration_in_seconds          integer,
  medium_stress_duration_in_seconds       integer,
  high_stress_duration_in_seconds         integer,

  floors_climbed                          integer,

  moderate_intensity_duration_in_seconds  integer,
  vigorous_intensity_duration_in_seconds  integer,

  min_heart_rate                          integer,
  average_heart_rate                      integer,
  max_heart_rate                          integer,
  resting_heart_rate                      integer,

  time_offset_heart_rate_samples          jsonb,  -- Map<String,Integer>

  stress_duration_in_seconds              integer
);
CREATE INDEX IF NOT EXISTS idx_garmin_daily_summaries_user        ON garmin_daily_summaries (user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_daily_summaries_providerusr ON garmin_daily_summaries (provider_user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_daily_summaries_date        ON garmin_daily_summaries (calendar_date);


CREATE TABLE IF NOT EXISTS garmin_hrv_summaries (
  id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  summary_id                    text,

  provider_user_id              text        NOT NULL,
  user_id                       uuid        NOT NULL,     -- FK -> users(id)

  calendar_date                 date,
  start_time_in_seconds         bigint,
  start_time_offset_in_seconds  integer,
  duration_in_seconds           integer,

  last_night_avg                integer,
  last_night5_min_high          integer,

  hrv_values                    jsonb       -- Map<String, Double>
);

CREATE INDEX IF NOT EXISTS idx_garmin_hrv_summaries_user        ON garmin_hrv_summaries (user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_hrv_summaries_providerusr ON garmin_hrv_summaries (provider_user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_hrv_summaries_date        ON garmin_hrv_summaries (calendar_date);


CREATE TABLE IF NOT EXISTS garmin_pulseox_summaries (
  id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  summary_id                    text,

  provider_user_id              text        NOT NULL,
  user_id                       uuid        NOT NULL,      -- FK -> users(id)

  calendar_date                 date,
  start_time_in_seconds         bigint,
  start_time_offset_in_seconds  integer,
  duration_in_seconds           integer,

  time_offset_spo2_values       jsonb        -- Map<String, Integer>
);
CREATE INDEX IF NOT EXISTS idx_garmin_pulseox_summaries_user        ON garmin_pulseox_summaries (user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_pulseox_summaries_providerusr ON garmin_pulseox_summaries (provider_user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_pulseox_summaries_date        ON garmin_pulseox_summaries (calendar_date);

CREATE TABLE IF NOT EXISTS garmin_sleep_summaries (
  id                                uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  summary_id                        text,

  provider_user_id                  text        NOT NULL,
  user_id                           uuid        NOT NULL,      -- FK -> users(id)

  calendar_date                     date,
  start_time_in_seconds             bigint,
  start_time_offset_in_seconds      integer,
  duration_in_seconds               integer,

  deep_sleep_duration_in_seconds    integer,
  light_sleep_duration_in_seconds   integer,
  rem_sleep_in_seconds              integer,
  awake_duration_in_seconds         integer,

  unmeasurable_sleep_in_seconds     integer,

  validation                        text,

  time_offset_sleep_spo2            jsonb,    -- Map<String, Integer>
  sleep_scores                      jsonb,    -- Map<String, Object>
  overall_sleep_score               jsonb,    -- Map<String, Object>
  naps                              jsonb     -- List<NapSummary>
);
CREATE INDEX IF NOT EXISTS idx_garmin_sleep_summaries_user        ON garmin_sleep_summaries (user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_sleep_summaries_providerusr ON garmin_sleep_summaries (provider_user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_sleep_summaries_date        ON garmin_sleep_summaries (calendar_date);


CREATE TABLE IF NOT EXISTS garmin_stress_summaries (
  id                                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  summary_id                         text,

  provider_user_id                   text        NOT NULL,
  user_id                            uuid        NOT NULL,     -- FK -> users(id)

  calendar_date                      date,
  start_time_in_seconds              bigint,
  start_time_offset_in_seconds       integer,
  duration_in_seconds                integer,

  time_offset_stress_level_values    jsonb,
  time_offset_body_battery_values    jsonb,
  body_battery_activity_events       jsonb,

  created_at                         timestamptz NOT NULL DEFAULT now(),
  updated_at                         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_garmin_stress_summaries_user        ON garmin_stress_summaries (user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_stress_summaries_providerusr ON garmin_stress_summaries (provider_user_id);
CREATE INDEX IF NOT EXISTS idx_garmin_stress_summaries_date        ON garmin_stress_summaries (calendar_date);

-- 8) Subscriptions (V11)
CREATE TABLE IF NOT EXISTS subscriptions (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                uuid          NOT NULL,                         -- FK to users.id
  stripe_subscription_id text          NOT NULL,                         -- UNIQUE
  stripe_customer_id     text          NOT NULL,
  stripe_schedule_id     text,
  product_key            text          NOT NULL,
  price_id               text          NOT NULL,
  quantity               integer       NOT NULL DEFAULT 1,
  status                 text          NOT NULL,                         -- 'incomplete','trialing','active',...
  current_period_start   timestamptz,
  current_period_end     timestamptz,
  cancel_at              timestamptz,
  canceled_at            timestamptz,
  amount_cents           bigint,
  currency               text,
  "interval"             text,                                           -- quoted: reserved-ish word
  meta                   jsonb,
  created_at             timestamptz   NOT NULL DEFAULT now(),
  updated_at             timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user   ON subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions (status);


-- TABLE TO KEEP TRACK OF SYNCS PER PROVIDER PER USER
CREATE TABLE IF NOT EXISTS user_provider_sync_state (
  id                           UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id                      UUID        NOT NULL,
  provider_id                  smallint    NOT NULL,
  dataset                      TEXT        NOT NULL,  -- e.g. 'sleep','hrv','daily','stress','pulseox','activities','oura_sleep',...

  earliest_synced_date         DATE        NULL,      -- oldest date we have
  latest_synced_date           DATE        NULL,      -- newest date we have

  backfill_status              TEXT        NOT NULL DEFAULT 'IDLE', -- IDLE|RUNNING|SUCCESS|ERROR
  backfill_started_at          TIMESTAMPTZ NULL,
  backfill_finished_at         TIMESTAMPTZ NULL,

  last_incremental_received_at TIMESTAMPTZ NULL,      -- last webhook “we saw new data” (optional but useful)

  created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Relationships
  CONSTRAINT fk_upss_user     FOREIGN KEY (user_id)     REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT fk_upss_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,

  -- One row per (user, provider, dataset)
  CONSTRAINT uq_upss_user_provider_dataset UNIQUE (user_id, provider_id, dataset),

  -- Sanity checks
  CONSTRAINT ck_upss_backfill_status CHECK (backfill_status IN ('IDLE','RUNNING','SUCCESS','ERROR')),
  CONSTRAINT ck_upss_date_range CHECK (
    earliest_synced_date IS NULL OR latest_synced_date IS NULL OR earliest_synced_date <= latest_synced_date
  )
);

-- Fast lookups by user, and by user+provider (the UNIQUE also helps).
CREATE INDEX IF NOT EXISTS idx_upss_user            ON user_provider_sync_state (user_id);
CREATE INDEX IF NOT EXISTS idx_upss_user_provider   ON user_provider_sync_state (user_id, provider_id);


-- 9) Helpful triggers (optional)
-- Keep updated_at fresh
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at'
  ) THEN
    CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $f$
    BEGIN
      NEW.updated_at := now();
      RETURN NEW;
    END;
    $f$ LANGUAGE plpgsql;
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.triggers
    WHERE event_object_table = 'users' AND trigger_name = 'trg_users_updated_at'
  ) THEN
    CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;