---- V4__rename_username_to_email.sql
--
---- 1) Add email (citext) if it doesn't exist
--DO $$
--BEGIN
--  IF NOT EXISTS (
--    SELECT 1
--    FROM information_schema.columns
--    WHERE table_name = 'users' AND column_name = 'email'
--  ) THEN
--    ALTER TABLE users ADD COLUMN email CITEXT;
--  END IF;
--END
--$$ LANGUAGE plpgsql;
--
---- 2) Backfill email from username when email is NULL
--UPDATE users
--SET email = username
--WHERE email IS NULL;
--
---- 3) Ensure NOT NULL on email
--ALTER TABLE users ALTER COLUMN email SET NOT NULL;
--
---- 4) Create a unique constraint on email (if missing)
--DO $$
--BEGIN
--  IF NOT EXISTS (
--    SELECT 1
--    FROM pg_constraint
--    WHERE conname = 'uk_users_email'
--  ) THEN
--    ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);
--  END IF;
--END
--$$ LANGUAGE plpgsql;
--
---- 5) Drop any old UNIQUE on username (if it exists, name may vary)
--DO $$
--DECLARE
--  c RECORD;
--BEGIN
--  FOR c IN
--    SELECT conname
--    FROM pg_constraint
--    WHERE conrelid = 'users'::regclass
--      AND contype = 'u'
--      AND conname ILIKE '%username%'
--  LOOP
--    EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', c.conname);
--  END LOOP;
--END
--$$ LANGUAGE plpgsql;
--
---- 6) (Optional) drop the username column after you’ve updated the code and data paths
--ALTER TABLE users DROP COLUMN username;