services:
  app:
    build:
      context: .
    container_name: ${DEV_APP_NAME}
    ports:
      - "${DEV_APP_PORT}:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DEV_DB_URL: ${DEV_DB_URL}
      DEV_DB_USER: ${DEV_DB_USER}
      DEV_DB_PASSWORD: ${DEV_DB_PASSWORD}
      DEV_APP_NAME: ${DEV_APP_NAME}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_REDIRECT_URL: ${STRAVA_REDIRECT_URL}
      STRAVA_WEBHOOK_VERIFY_TOKEN: ${STRAVA_WEBHOOK_VERIFY_TOKEN}
      FITBIT_CLIENT_SECRET: ${FITBIT_CLIENT_SECRET}
      FITBIT_CLIENT_ID: ${FITBIT_CLIENT_ID}
      FITBIT_REDIRECT_URL: ${FITBIT_REDIRECT_URL}
      DEV_FRONTEND_URL: ${DEV_FRONTEND_URL}
      DEV_BACKEND_URL: ${DEV_BACKEND_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL_DAYS: ${JWT_TTL_DAYS}
      JWT_ISSUER: ${JWT_ISSUER}
      SES_HOST_NAME: ${SES_HOST_NAME}
      SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
      SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
      AUTH_MAGIC_TTL_MINUTES: ${AUTH_MAGIC_TTL_MINUTES}

  postgres:
    container_name: ${DEV_DB_CONTAINER_NAME}
    ports:
      - "${DEV_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DEV_DB}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}