services:
  app:
    build:
      context: .
    container_name: ${TEST_APP_NAME}
    ports:
      - "${TEST_APP_PORT}:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DEV_DB_URL: ${TEST_DB_URL}
      DEV_DB_USER: ${TEST_DB_USER}
      DEV_DB_PASSWORD: ${TEST_DB_PASSWORD}
      DEV_APP_NAME: ${TEST_APP_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  postgres:
    container_name: ${TEST_DB_CONTAINER_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${TEST_DB}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}